apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-deployment
  labels:
    app: insurance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insurance
  template:
    metadata:
      labels:
        app: insurance
    spec:
      containers:
      - name: insurance-container
        image: yourdockerhubusername/insurance:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: insurance-service
spec:
  type: NodePort
  selector:
    app: insurance
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30091
